approve_by_comment: true
approve_regex: ^Approved
reject_regex: ^Rejected
reset_on_push: true
author_approval: ignored
reviewers:
  members:
  - roncrush
  - bhopewell
  - silentreverb
  - stoplime
  name: default
  required: 1
