## VM settings ##
dist: trusty # Ubuntu distro to use
sudo: required # enable admin rights in VM
services:
  - docker
notifications:
env:
  global:
    - CI_SOURCE_PATH=$(pwd) # Save default repo location to environment variable 

#branches:
#  only:
#   - master

# NOTE: The build lifecycle on Travis.ci is something like this:
#    before_install
#    install
#    before_script
#    script
#    after_success or after_failure
#    after_script
#    OPTIONAL before_deploy
#    OPTIONAL deploy
#    OPTIONAL after_deploy

install:
  - docker pull shadysource/xenial

before_script:
  - mkdir -p ~/ros/catkin_ws/
  - cd ~/ros/catkin_ws && mv $CI_SOURCE_PATH ~/ros/catkin_ws/src

script:
  - docker run -v ~/ros/catkin_ws/src:/root/catkin_ws/src --name build shadysource/xenial /bin/bash -c "cd ~/catkin_ws; catkin_make -j$(nproc)"
