## VM settings ##
dist: trusty # Ubuntu distro to use
sudo: required # enable admin rights in VM
services:
  - docker
notifications:
  email: # Email these scrubs when builds/tests fails
    - bhopewel@students.kennesaw.edu
    - sali37@students.kennesaw.edu
    - nschulz@students.kennesaw.edu
env:
  global:
    - CI_SOURCE_PATH=$(pwd) # Save default repo location to environment variable 

branches:
  only:
   - master

# NOTE: The build lifecycle on Travis.ci is something like this:
#    before_install
#    install
#    before_script
#    script
#    after_success or after_failure
#    after_script
#    OPTIONAL before_deploy
#    OPTIONAL deploy
#    OPTIONAL after_deploy

install:
  - docker pull ksuart/catkin-build:depends-ros

before_script:
  - mkdir -p ~/ros/catkin_ws/
  - cd ~/ros/catkin_ws && mv $CI_SOURCE_PATH ~/ros/catkin_ws/src

script:
  - docker run -v ~/ros/catkin_ws/src:/root/ros/catkin_ws/src --name build ksuart/catkin-build:depends-ros /bin/bash -c "cd ~/opencv/cv3-release/; sudo make -j4 install; cm --pkg observer; sudo make -j4 uninstall; cd ~/opencv/cv2-release/; sudo make -j4 install; cm"
