## VM settings ##
dist: trusty # Ubuntu distro to use
sudo: required # enable admin rights in VM
services:
  - docker
notifications:
  email: # Email these scrubs when builds/tests fails
    - bhopewel@students.kennesaw.edu
    - sali37@students.kennesaw.edu
    - nschulz@students.kennesaw.edu
env:
  global:
    - CI_SOURCE_PATH=$(pwd) # Save default repo location to environment variable 
    - OPENCV_VER=2.4.9

branches:
  only:
   - master

# NOTE: The build lifecycle on Travis.ci is something like this:
#    before_install
#    install
#    before_script
#    script
#    after_success or after_failure
#    after_script
#    OPTIONAL before_deploy
#    OPTIONAL deploy
#    OPTIONAL after_deploy

install:
  - if [ $OPENCV_VER == 2.4.9 ]; then docker pull ksuart/catkin-build:depends-ros-cv2; fi
  - if [ $OPENCV_VER == 3.1.0 ]; then docker pull ksuart/catkin-build:depends-ros-cv3; fi

before_script:
  - mkdir -p ~/ros/catkin_ws/
  - cd ~/ros/catkin_ws && mv $CI_SOURCE_PATH ~/ros/catkin_ws/src

script:
  - if [ $OPENCV_VER == 2.4.9 ]; then docker run -v ~/ros/catkin_ws/src:/root/ros/catkin_ws/src --name build ksuart/catkin-build:depends-ros-cv2 /bin/bash -c "cd ~/ros/catkin_ws; catkin_make -j8 --pkg mavros; catkin_make -j8 --pkg mavros_msgs; catkin_make -j8 --pkg mavros_extras; catkin_make -j8 --pkg ros_opencv; cd src; ls; cd mavros; ls; cd mavros; ls; cmake .; make -j8; make install; cd ~/ros/catkin_ws; catkin_make -j8;"; fi
  - if [ $OPENCV_VER == 3.1.0 ]; then docker run -v ~/ros/catkin_ws/src:/root/ros/catkin_ws/src --name build ksuart/catkin-build:depends-ros-cv3 /bin/bash -c "cd ~/ros/catkin_ws; catkin_make -j8 --pkg mavros; catkin_make -j8 --pkg mavros_msgs; catkin_make -j8 --pkg mavros_extras; catkin_make -j8 --pkg ros_opencv; catkin_make -j8"; fi
